# Generated by Django 5.1.1 on 2024-10-28 14:12

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PizzaCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_pizza_category",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Pizzeria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=400)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        default="default_pizzeria.jpg",
                        upload_to="pizzeria_profile_pictures/",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("hot_slice", models.BooleanField(default=False)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.city"
                    ),
                ),
                ("pizza_categories", models.ManyToManyField(to="pizza.pizzacategory")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pizzeria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pizza.pizzeria"
                    ),
                ),
            ],
            options={
                "ordering": ["-create_date"],
            },
        ),
        migrations.CreateModel(
            name="PizzeriaVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField(auto_now_add=True)),
                (
                    "pizzeria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pizza.pizzeria"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date"],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ]
                    ),
                ),
                ("last_update", models.DateField(auto_now=True)),
                (
                    "pizzeria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pizza.pizzeria"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_update"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.CharField(max_length=255)),
                ("last_update", models.DateField(auto_now=True)),
                ("create_date", models.DateField(auto_now_add=True)),
                (
                    "pizzeria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pizza.pizzeria"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_update"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateField(auto_now_add=True)),
                (
                    "pizzeria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pizza.pizzeria"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-create_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="pizzeria",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("address"),
                name="unique_pizzeria",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "pizzeria"), name="unique_favorite"
            ),
        ),
        migrations.AddConstraint(
            model_name="pizzeriavisit",
            constraint=models.UniqueConstraint(
                fields=("user", "pizzeria", "visit_date"), name="unique_pizzeria_visit"
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("user", "pizzeria"), name="unique_rating"
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 8)),
                name="rating_range_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "pizzeria"), name="unique_review"
            ),
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                fields=("user", "pizzeria"), name="unique_wishlist"
            ),
        ),
    ]
